# Generated by Django 5.2.12 on 2026-03-26 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('routine', '0003_routineentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='category.category'),
        ),
        migrations.AlterField(
            model_name='routineentry',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routineentries', to='routine.routine'),
        ),
    ]
