# Generated by Django 5.2.12 on 2026-03-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_alter_routine_category_alter_routineentry_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
