# Generated by Django 5.2.12 on 2026-04-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0006_alter_routine_category_alter_routineentry_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='scheduled_at',
            field=models.TimeField(default='00:00'),
        ),
    ]
