# Generated by Django 5.2.12 on 2026-03-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
